### ISSUE TITLE
Conflicts with older WebXR extension in Chrome

### ISSUE THREAD

**Issue by kevinjardine** [meta-quest/immersive-web-emulator#12]
In Chrome (at least Chrome on Windows latest version) you need to deactivate the older extension or it will consume all the events and the app will not respond to headset movements in the new extension.

**Comment by felixtrz** [comment]
Great call out, apparently the Immersive Web Emulator and the [WebXR API Emulator](https://github.com/MozillaReality/WebXR-emulator-extension) by Mozilla are not compatible with each other (for reasons not known to me), when both are active, neither will work. So you will have to disable one to use the other.

Since it's very unlikely a user needs to use both at the same time, this is not a high-priority item for me to look into and fix at the moment, but please let me know if you do need to do so.

**Comment by felixtrz** [comment]
And a big thank you to @kevinjardine for bringing this to our attention!
