### ISSUE TITLE
Emulator room/cube appears in-scene while emulator is on

### ISSUE THREAD

**Issue by intentmoose** [meta-quest/immersive-web-emulator#17]
The hex room/cube appears in the scene
![image](https://user-images.githubusercontent.com/29212215/228318063-687129b4-976c-49bf-9782-9780089de313.png)

Developing in AFRAME

**Comment by felixtrz** [comment]
This is intentional. The grid room should only be visible when you are in AR mode, which should give you pass-through background on headset. The grid room is to emulate the pass-through background. The dimension of the grid room can be customized with the space width/height/depth option in the emulator UI, and the grid room supplies XRPlanes information accordingly to the WebXR app.

**Comment by intentmoose** [comment]
Understood, thanks.
Thats useful.
