### ISSUE TITLE
support for bHaptics tact gloves

### ISSUE THREAD

**Issue by addy1997** [meta-quest/immersive-web-emulator#26]
Hi @RaananW, 

Can I add support to the Oculus web browser to enable it to detect my haptic gloves? I am using[ tact gloves ](https://github.com/bhaptics/tact-js) to get haptic feedback upon touching any object in the VR scene.

**Comment by RaananW** [comment]
I guess you wanted to ping @felixtrz? He is the mastermind behind this emulator

**Comment by RaananW** [comment]
well, pinging me will probably not help :-)

This is probably the wrong repository to discuss this anyhow. Try reaching out to the oculus browser team on twitter or some other social network, you might have better luck

**Comment by felixtrz** [comment]
Hello @addy1997, my apologies for the delay in my response. As @RaananW pointed out, this thread may not be the most appropriate platform for discussing the addition of haptic glove support to the Meta Quest browser rather than the emulator. I would recommend reaching out to [Dave Hill](https://twitter.com/00davehill00?s=20), our engineering manager, for a more in-depth conversation. 

While I can't speak on Dave's behalf, our team is generally receptive to the idea of adding support for devices that can interface via the WebXR device API. However, we are less likely to make exceptions for non-standard XR input devices. If the haptic gloves can be presented as a standard gamepad through the standard [gamepad API](https://www.w3.org/TR/gamepad/), which we support, it should already function correctly.

**Comment by addy1997** [comment]
@RaananW and @felixtrz, I am sorry for raising the issue on the wrong repository. Thanks for the tip. I'll definitely try to reach out to the Oculus team and Dave for more clarity.

Cheers
Adwait
