### ISSUE TITLE
Unexpected `press` or `selectstart` behaviour 

### ISSUE THREAD

**Issue by marwie** [meta-quest/immersive-web-emulator#53]
Hi, see attached video

expected: 
- down and holding "press" button in simulator presses the button (value increases to 1) - triggering "selectstart"
- releasing "press" button releases the button (values decreases to 0) - triggering "selectend"

actual:
- down and holding "press" button does have no imediate effect
- releasing "press" button increases and decreases value and triggers "selectstart" and "selectend" at once

**Comment by felixtrz** [comment]
This behavior is intentional by design. The 'press' button is not intended for a press-and-hold action. Instead, it executes a complete press-and-release sequence, as demonstrated by the animation of the range selector on the side. If users wish to maintain a specific value, they should adjust the range selector on the side rather than pressing and holding the button. This not only keeps the button pressed, but also provides full control over the value at which the trigger or grip button should be held.
